<?xml version="1.0" encoding="utf-8"?><Database Name="TVItems" Class="TVItemsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=TVItems;Integrated Security=True" SettingsObjectName="TV.Data.Properties.Settings" SettingsPropertyName="TVItemsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TVItems" Member="TVItems">
    <Type Name="TVItem">
      <Column Name="ItemNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MemberCost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ShortDescription" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ClassCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubClassCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VendorName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="UPC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LongDescription" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ChangeLogs" Member="ChangeLogs">
    <Type Name="ChangeLog">
      <Column Name="ItemNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChangeType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FromValue" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="ToValue" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>